#"api_key": "e6fe7347"
#"api_secret": "vLR4xOjA1DsU90gF"
udid = "emulator-5554"
platformName = "Android"
platformVersion = "3.1.0"
appPackage = "io.appium.android.apis"
    #Can be found in AndroidManifest.xml file, appActivity will be that activity that contains both LAUNCHER and MAIN
appActivity = ".ApiDemos"
deviceName = "emulator-5554"
